### ISSUE TITLE
Could NOT find wxWidgets

### ISSUE THREAD

**Issue by xiang-tao** [rgleason/AISradar_pi#24]
When I run cmake ..
error：
![屏幕截图 2024-05-06 212548](https://github.com/rgleason/AISradar_pi/assets/75120277/9adc4f06-25fd-46bf-83c2-ae4bc7e0114a)

My system is Ubuntu22.04, and I installed wxWidgets, but this error keeps happening. I don’t know the reason. I hope you can help me, I will be grateful.

**Comment by pacho2** [comment]
It looks similar to:
https://github.com/seandepagnier/rtlsdr_pi/issues/25

**Comment by Quentin-xue** [comment]
you can  try 

`
corey@fcyswrd-15:~/opencpn/opencpnbuildroot/opencpn_plugins/statusbar_pi/buildroot$ export BUILD_GTK3=TRUE
corey@fcyswrd-15:~/opencpn/opencpnbuildroot/opencpn_plugins/statusbar_pi/buildroot$ cmake ..
`

**Comment by Quentin-xue** [comment]
![image](https://github.com/user-attachments/assets/703ac89d-310f-497b-917a-53aff8eb1880)

**Comment by rgleason** [comment]
I am not a linux user, but you should set your dev environment to find wxwidgets.
This is really not a problem with AIS radar. Thus closing.
