### ISSUE TITLE
Ubuntu 18.04 and Flatpak: No Preferences or Icon for AISview installed in flatpak

### ISSUE THREAD

**Issue by filochard** [rgleason/AISradar_pi#5]
Hi Rick 
Inside Flatpak, once AISradar installed and activated,  the AISview icon doesn't appear in the icons tray of opencpn (even if, in preferences, you set it to show its icon )

NB It appears inside a linux installation  based on rpm with the Verezano's code from july 2020 tagged version v1.2

**Comment by rgleason** [comment]
Have updated AISradar here, but I have not changed any icons, however I am wondering if this fixes it.
https://github.com/rgleason/AISradar_pi

Deploying to here  https://cloudsmith.io/~opencpn/repos/aisradar-beta/packages/
look for version 1.2.6.2

If not, I'll dig into that.

**Comment by rgleason** [comment]
Flatpak and Ubuntu 18.04
Preferences button is also greyed out and not available.
Bitmaps directory is not copied to tarball.  Needs to move under data dir or Icons dir which are copied by 
Have tried copying the bitmaps dir into the tarball and using "Import Plugin" but that does not seem to fix it.
Still  missing a symbol of some sort in the opencpn.log

**Comment by rgleason** [comment]
@filochard    can you try it again?  Will be in PIM soon....
https://github.com/OpenCPN/plugins/pull/374

**Comment by filochard** [comment]
Hi
I have just downloaded the 1.2.7.0 flatpak version from here : 
 https://cloudsmith.io/~opencpn/repos/aisradar-prod/packages/
and installed it
Everything is OK

**Comment by rgleason** [comment]
Great closing
